# Generated by Django 6.0.3 on 2026-05-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True, default="", help_text="A short bio about yourself"
            ),
        ),
    ]
